### ISSUE TITLE
Evaluasi

### ISSUE THREAD

**Issue by ghost** [gunadarma-academy/asde-papier#11]
Ada beberapa evaluasi _mockup_ yang sudah dibuat. Yaitu:
- [x]  Ini lebih baik dibuat jadi one line text, jadi ga bisa dienter ke bawah
  ![2](https://cloud.githubusercontent.com/assets/4651012/13975756/5ec8ec32-f0eb-11e5-825f-06308b6ddc40.png)
- [x]  "Ganti Tantangan" lebih baik dihilangkan
  ![5](https://cloud.githubusercontent.com/assets/4651012/13975669/6458a788-f0ea-11e5-81ac-ea451583e8c6.gif)
- [x] Lebih baik ditambahkan informasi semacam "masukkan pemain ke 1 dari 5 pemain."
  ![2](https://cloud.githubusercontent.com/assets/4651012/13975756/5ec8ec32-f0eb-11e5-825f-06308b6ddc40.png)

**Comment by angellicaos** [comment]
Menanggapi:
1. Oke, akan ditambahkan atribut single line.
2. Oke, seperti keputusan kemarin ya, jadi nggak bisa ganti tantangan.
3. Masih kurang mengerti untuk bagian ini, masukkan pemain ke- ... itu di halaman ini kan tidak ada? Tapi cuma masukkan jumlah pemain saja. Sepertinya bukan mockup halaman ini ya maksudnya?

**Comment by ghost** [comment]
wkwkwkw oiya anjir yang ketiga itu gambarnya sama kayak yang pertama. cek update nya ya

**Comment by angellicaos** [comment]
Siap laksanakan! Bentar gue cari dulu caranya ya.. hahaha

**Comment by angellicaos** [comment]
Task no 1, completed.

**Comment by angellicaos** [comment]
Task no 2, completed. But hasn't been committed yet.

**Comment by angellicaos** [comment]
Task no 3, completed.
All are completed, have already been committed, but have not been pull to upstream master.

**Comment by angellicaos** [comment]
Udah diubah di codingan tapi belom di pull ke master yang task nomor 3 ya...

**Comment by ghost** [comment]
oke Njel

**Comment by ghost** [comment]
done
