### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by ghost** [gunadarma-academy/asde-papier#16]
Editing use case diagram. Ditambahkan _extend/include_
![use_case](https://cloud.githubusercontent.com/assets/4651012/13986476/356f40bc-f135-11e5-9cfc-25047825fe91.png)

**Comment by sandyin3d** [comment]
Hola mas, sudah aku perbarui ya use case terbarunya, tinggal dicommit aja biar gak batuk hehe itu komix ya :))

**Comment by ghost** [comment]
y
