### ISSUE TITLE
[Eva-Pro1] Mengacak Ulang Target dan Melanjutkan Permainan

### ISSUE THREAD

**Issue by sandyin3d** [gunadarma-academy/asde-papier#18]
Masih terdapat kekurangan pada percobaan internal prototype 1 sebelum dibuatkan UATnya. Berikut penjelasannya.
- [ ] Pada halaman ini (setelah mengacak tantangan dan nama target) hanya terdapat 2 _button_ saja, yaitu _button_ "Ulang".

![prob-1](https://cloud.githubusercontent.com/assets/17759371/14061047/ac234940-f3a8-11e5-8799-796461434fb3.PNG)

Sebaiknya dibuat seperti requirement yang telah disepakati dan mockup yang ada seperti gambar di bawah.

![6](https://cloud.githubusercontent.com/assets/17759371/14061103/14c0736e-f3aa-11e5-86fa-bae068f792c2.PNG)

Berikut penjelasannya:
1. Saat mengklik _button_ "Ulang", halaman akan mengarah ke halaman pengacakan tantangan jujur /  berani.
2. Apabila diklik _button_ "Selanjutnya", maka akan mengarah ke halaman pengacakan nama peserta lagi (menentukan peserta yang akan ditantang).

Sekian penjelasannya, mohon untuk ditindaklanjuti. Apabila ada yang kurang dipahami mohon ditanyakan hehe

**Comment by angellicaos** [comment]
Padahal gue udah nanya dan bahas waktu itu di whatsapp soal button _(masih ngambek)_
Jadi sesuai mock up itu ada dua button? Ok.
Kalau tulisan masih mau disamain juga nggak? Itu memang gue buat begitu karena tantangan kan panjang tulisannya, jadi kalo dipaksain di tengah (kotak kuning) sama nama targetnya jadi numpuk, kalo tiga baris gitu jadi jelek. makanya gue buat kayak di atas. Oh tapi memang yg bagian ini gue nggak konsultasi dulu sih ke kalian. Maaf yak.

**Comment by sandyin3d** [comment]
hwaaa emang ya njels :" maap mungkin ke skip huhu soalnya waktu itu gue juga sempet bahas ini juga ke mahen, jadi gue kira udah fix aja :" maapkeun daku.

Untuk tulisan yang di kuningnya itu, which means random tantangan sama nama objek yang ditantangnya itu dipisah halamannya, still okay. Bener juga sih kalo ternyata tantangannya panjang jadi agak ganggu hehe. semangat enjellsss :") ku sebnernya ndak mau merepotkan programmer, tapi.... yaa gimana ku juga bingung huhu miskom aja kita

**Comment by ghost** [comment]
maafin Njel :(

Iya intinya pengacakan tantangan sama pengacakan nama di halaman berbeda aja
