### ISSUE TITLE
[Eva-Pro1] Penambahan Header untuk Halaman Pop-up "Help" dan "Pengembang"

### ISSUE THREAD

**Issue by sandyin3d** [gunadarma-academy/asde-papier#20]
Sebenernya ini udah fine aja, tergantung sama Enjel apakah ada kesulitan dalam mengimplementasikannya.

![prob-2](https://cloud.githubusercontent.com/assets/17759371/14061446/cd158122-f3b2-11e5-9002-41d87387fccb.PNG)

Tapi kalo memang mau tetap seperti yang direncanakan pada mockup awal juga monggo hehe enaknya enjelikah aja

![prob-3](https://cloud.githubusercontent.com/assets/17759371/14061453/fb73aff8-f3b2-11e5-89e9-d6264ee48621.PNG)
- [ ] Pada halaman pop-up ini terdapat gambar headernya
- [ ] Entah cuma di bluestack gue doang atau gimana hwhawhaha soalnya button "Tutup" nya nggak terlalu ada di kanan gitu :") kalo emang di semua device ternyata udah fine yowes emang bluestacknya cacat lol

Thank youuuuhhh njelikah

**Comment by ghost** [comment]
Njel @angellicaos
