### ISSUE TITLE
Ubah jadi STRING ONLY dan BUAT TOMBOL RESET

### ISSUE THREAD

**Issue by ghost** [gunadarma-academy/asde-papier#21]
- [x] Njel ini tolong diubah jadi  _user_ bisa masukin string aja yakk ![2](https://cloud.githubusercontent.com/assets/4651012/14066011/3be2d832-f469-11e5-80b2-29f30004b2df.png)
- [x] tolong dibuatkan tombol reset hiihihihi ![12](https://cloud.githubusercontent.com/assets/4651012/14071407/7873207a-f4de-11e5-87fe-fcfdd7527122.png)

**Comment by angellicaos** [comment]
Sudah. Tinggal di push ke github.

**Comment by ghost** [comment]
okaayyy

**Comment by ghost** [comment]
done
