### ISSUE TITLE
Rangkuman Evaluasi Prototype 1

### ISSUE THREAD

**Issue by ghost** [gunadarma-academy/asde-papier#23]
Adapun hasil evaluasi dari feedback untuk prototype 1 adalah:
- [ ] Tombol back
- [x] Icon aplikasi JURANI
- [x] Percepat pengacakan
- [ ] Keyboard "LANJUT"
- [x] Perbesar _font_
- [x] Melakukan _filter_ terhadap nama yang dimasukkan, jika sudah ada nama yang sama maka pemain harus memasukkan nama yang lain
- [ ] Perbanyak jenis tantangan s/d 30 tantangan
- [x] _Button_ "ULANG" dibuat _raised button_
- [x] Edit Bahasa Indonesia dan Bahasa Inggris yang digunakan secara campur
- [x] _Help_-nya _numbering_ dan sekuensial
- [x] Dikasih _dialog_ pada saat _reset_ aplikasi "Apakah kamu yakin ingin me-reset permainan?" 
- [ ] Setiap di-”back”, memberikan pop up ’mau keluar?’ ya/tidak 
- [ ] _Style_ di status bar

Tolong ceklis kalo udah dikerjakan

**Comment by angellicaos** [comment]
Edit bahasa indonesia dan bhs inggris yg digunakan secara campur di bagian melihat petunjuk permainan itu maksudnya ada arahan dalam bahasa indo dan inggris atau bagaimana ya?

**Comment by ghost** [comment]
Hmm bukan sih Njel, itu maksudnya kayak yang tadi udah kita diskusiin wkwkw apaan yakk, mungkin gini kayak misalnya untuk bantuan dalam permainan itu bisa lo kasih judul HELP, tapi petunjuknya Bahasa Indonesia, itu maksudnya Njelss @angellicaos @thunderkee @sandyin3d
